name: Run tests and linting
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
      - uses: biomejs/setup-biome@v2.7.1
      - uses: actions/checkout@v7
      - name: Install Dependencies
        run: bun install
      - name: Run Tests
        run: bun test
      - name: Run lint
        run: bun run lint
      
